//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STORE_APP.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class APPOINTMENT
    {
        public int APPOINTMENT_ID { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        [Required(ErrorMessage = "Rotation should not be empty")]
        public string ROTATION { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        [Required(ErrorMessage = "Clock should not be empty")]
        public string CLOCK { get; set; }
        public Nullable<int> CAR_CATEGORY_ID { get; set; }
        [Required(ErrorMessage = "Activity should not be empty")]
        [Range(0, 1, ErrorMessage = "Activity should not be 0,1")]
        public Nullable<int> IS_ACTIV { get; set; }
        public Nullable<System.DateTime> C_DATE { get; set; }
        public Nullable<System.DateTime> U_DATE { get; set; }

        public virtual CARS_CATEGORY CARS_CATEGORY { get; set; }
        public virtual CUSTOMERS CUSTOMERS { get; set; }

    }
}
