//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STORE_APP.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CARS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CARS()
        {
            this.SALES_HISTORY = new HashSet<SALES_HISTORY>();
        }

        public int CAR_ID { get; set; }
        public Nullable<int> CAR_CATEGORY_ID { get; set; }
        [Required(ErrorMessage = "Number Plate should not be empty")]
        public string CAR_NUMBER_PLATE { get; set; }
        [Required(ErrorMessage = "Activity should not be empty")]
        [Range(0, 1, ErrorMessage = "Activity should not be 0,1")]
        public Nullable<int> IS_ACTIV { get; set; }
        public Nullable<System.DateTime> C_DATE { get; set; }
        public Nullable<System.DateTime> U_DATE { get; set; }
        [Required(ErrorMessage = "Shassis Code should not be empty")]
        [StringLength(17, ErrorMessage = "Shassis Code Must Be 17 Digit")]
        public string CAR_SHASSIS_CODE { get; set; }

        public virtual CARS_CATEGORY CARS_CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALES_HISTORY> SALES_HISTORY { get; set; }
    }

}
