//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STORE_APP.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CARS_INFORMATION
    {
        [Required(ErrorMessage = "Number Plate should not be empty")]
        public string CAR_NUMBER_PLATE { get; set; }
        [Required(ErrorMessage = "Information should not be empty")]
        public string INFORMATION { get; set; }
        public Nullable<System.DateTime> LAST_MAINTANCE_DATE { get; set; }
        public Nullable<System.DateTime> NEXT_MAINTANCE_DATE { get; set; }
        [Required(ErrorMessage = "Activity should not be empty")]
        [Range(0, 1, ErrorMessage = "Activity should not be 0,1")]
        public Nullable<int> IS_ACTIV { get; set; }
        public Nullable<System.DateTime> C_DATE { get; set; }
        public Nullable<System.DateTime> U_DATE { get; set; }
        [Required(ErrorMessage = "Kilometer should not be empty")]
        public Nullable<int> KILOMETER { get; set; }
        public int CAR_INFORMATION_ID { get; set; }
        [Required(ErrorMessage = "Shassis Code should not be empty")]
        public string CAR_SHASSIS_CODE { get; set; }
    }
}
