//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STORE_APP.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CUSTOMERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUSTOMERS()
        {
            this.APPOINTMENT = new HashSet<APPOINTMENT>();
            this.SALES_HISTORY = new HashSet<SALES_HISTORY>();
        }

        public int CUSTOMER_ID { get; set; }
        [Required(ErrorMessage = "Name should not be empty")]
        public string NAME { get; set; }
        [Required(ErrorMessage = "Surname should not be empty")]
        public string SURNAME { get; set; }
        [Required(ErrorMessage = "Phone should not be empty")]
        public string PHONE { get; set; }
        [Required(ErrorMessage = "E-Mail should not be empty")]
        public string EMAIL { get; set; }
        public string COMPANY_NAME { get; set; }
        [Required(ErrorMessage = "Activity should not be empty")]
        [Range(0, 1, ErrorMessage = "Activity should not be 0,1")]
        public Nullable<int> IS_ACTIV { get; set; }
        public Nullable<System.DateTime> C_DATE { get; set; }
        public Nullable<System.DateTime> U_DATE { get; set; }
        [Required(ErrorMessage = "Password should not be empty")]
        public string PASSWORD { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPOINTMENT> APPOINTMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALES_HISTORY> SALES_HISTORY { get; set; }
    }

}
