//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STORE_APP.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int requestID { get; set; }
        public Nullable<int> customerID { get; set; }
        public string message { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string subject { get; set; }
    }
}
