//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STORE_APP.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALES_HISTORY
    {
        public int SALES_ID { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        public Nullable<int> CAR_ID { get; set; }
        public Nullable<int> EMPLOYEE_ID { get; set; }
        public Nullable<int> EMPLOYEE_POINT { get; set; }
        public string ROTATION { get; set; }
        public Nullable<int> IS_ACTIV { get; set; }
        public Nullable<System.DateTime> C_DATE { get; set; }
        public Nullable<System.DateTime> U_DATE { get; set; }
    
        public virtual CARS CARS { get; set; }
        public virtual CUSTOMERS CUSTOMERS { get; set; }
        public virtual EMPLOYEES EMPLOYEES { get; set; }
    }
}
